# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: katalonTask@0
  inputs:
    version: '7.8.1'
    executeArgs: '-retry=0 -testSuitePath="Test Suites/Suite1" -executionProfile="main" -browserType="Chrome" -apikey="c46c0fe2-7f44-4171-b25f-cb2caa55d46e"'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
